// Studio = 1
// Outdoor = 2
// Vehicles = 3

export class PictureList {
    public pictures = [
        {
            id: '0',
            src: 'assets/img/DSC00150.jpg',
            thumb: 'assets/img/DSC00150.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '1',
            src: 'assets/img/DSC00183.jpg',
            thumb: 'assets/img/DSC00183.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '2',
            src: 'assets/img/DSC02818.jpg',
            thumb: 'assets/img/DSC02818.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '3',
            src: 'assets/img/DSC02829.jpg',
            thumb: 'assets/img/DSC02829.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '4',
            src: 'assets/img/DSC02835.jpg',
            thumb: 'assets/img/DSC02835.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '5',
            src: 'assets/img/DSC02903.jpg',
            thumb: 'assets/img/DSC02903.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '6',
            src: 'assets/img/DSC03108.jpg',
            thumb: 'assets/img/DSC03108.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '7',
            src: 'assets/img/DSC03121.jpg',
            thumb: 'assets/img/DSC03121.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '8',
            src: 'assets/img/DSC03125.jpg',
            thumb: 'assets/img/DSC03125.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '9',
            src: 'assets/img/DSC04771.jpg',
            thumb: 'assets/img/DSC04771.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '10',
            src: 'assets/img/DSC04818.jpg',
            thumb: 'assets/img/DSC04818.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '11',
            src: 'assets/img/DSC04831.jpg',
            thumb: 'assets/img/DSC04831.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '12',
            src: 'assets/img/DSC04891.jpg',
            thumb: 'assets/img/DSC04891.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '13',
            src: 'assets/img/DSC04904.jpg',
            thumb: 'assets/img/DSC04904.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '14',
            src: 'assets/img/DSC04907.jpg',
            thumb: 'assets/img/DSC04907.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '15',
            src: 'assets/img/DSC04940.jpg',
            thumb: 'assets/img/DSC04940.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '16',
            src: 'assets/img/DSC09101.jpg',
            thumb: 'assets/img/DSC09101.jpg',
            format: 0,
            subHtml: 'CarImage',
            kindOfShooting: 3,
        },
        {
            id: '17',
            src: 'assets/img/DSC00606.jpg',
            thumb: 'assets/img/DSC00606.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '18',
            src: 'assets/img/DSC00742.jpg',
            thumb: 'assets/img/DSC00742.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '19',
            src: 'assets/img/DSC00845-3.jpg',
            thumb: 'assets/img/DSC00845-3.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '20',
            src: 'assets/img/DSC01022.jpg',
            thumb: 'assets/img/DSC01022.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '21',
            src: 'assets/img/DSC01892-6.jpg',
            thumb: 'assets/img/DSC01892-6.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '22',
            src: 'assets/img/DSC01911.jpg',
            thumb: 'assets/img/DSC01911.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '23',
            src: 'assets/img/DSC01921.jpg',
            thumb: 'assets/img/DSC01921.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '24',
            src: 'assets/img/DSC03091.jpg',
            thumb: 'assets/img/DSC03091.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '25',
            src: 'assets/img/DSC03095.jpg',
            thumb: 'assets/img/DSC03095.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '26',
            src: 'assets/img/DSC03205.jpg',
            thumb: 'assets/img/DSC03205.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '27',
            src: 'assets/img/DSC03238.jpg',
            thumb: 'assets/img/DSC03238.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '28',
            src: 'assets/img/DSC03610.jpg',
            thumb: 'assets/img/DSC03610.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '29',
            src: 'assets/img/DSC03772.jpg',
            thumb: 'assets/img/DSC03772.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '30',
            src: 'assets/img/DSC04030.jpg',
            thumb: 'assets/img/DSC04030.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '31',
            src: 'assets/img/DSC04037.jpg',
            thumb: 'assets/img/DSC04037.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '32',
            src: 'assets/img/DSC04155.jpg',
            thumb: 'assets/img/DSC04155.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '33',
            src: 'assets/img/DSC04190.jpg',
            thumb: 'assets/img/DSC04190.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '34',
            src: 'assets/img/DSC04207.jpg',
            thumb: 'assets/img/DSC04207.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '35',
            src: 'assets/img/DSC04245.jpg',
            thumb: 'assets/img/DSC04245.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '36',
            src: 'assets/img/DSC04396.jpg',
            thumb: 'assets/img/DSC04396.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '37',
            src: 'assets/img/DSC05051.jpg',
            thumb: 'assets/img/DSC05051.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '38',
            src: 'assets/img/DSC06521.jpg',
            thumb: 'assets/img/DSC06521.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '39',
            src: 'assets/img/DSC06537.jpg',
            thumb: 'assets/img/DSC06537.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '40',
            src: 'assets/img/DSC07149 2.jpg',
            thumb: 'assets/img/DSC07149 2.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '41',
            src: 'assets/img/DSC07491-2.jpg',
            thumb: 'assets/img/DSC07491-2.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '42',
            src: 'assets/img/DSC07604-2.jpg',
            thumb: 'assets/img/DSC07604-2.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '43',
            src: 'assets/img/DSC07607.jpg',
            thumb: 'assets/img/DSC07607.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '44',
            src: 'assets/img/DSC07749.jpg',
            thumb: 'assets/img/DSC07749.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '45',
            src: 'assets/img/DSC08691.jpg',
            thumb: 'assets/img/DSC08691.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '46',
            src: 'assets/img/DSC08901.jpg',
            thumb: 'assets/img/DSC08901.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '47',
            src: 'assets/img/DSC08915.jpg',
            thumb: 'assets/img/DSC08915.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '48',
            src: 'assets/img/DSC09690.jpg',
            thumb: 'assets/img/DSC09690.jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '49',
            src: 'assets/img/IMG_0219(1).jpg',
            thumb: 'assets/img/IMG_0219(1).jpg',
            format: 0,
            subHtml: 'OutdoorImage',
            kindOfShooting: 2,
        },
        {
            id: '50',
            src: 'assets/img/DSC00288.jpg',
            thumb: 'assets/img/DSC00288.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '51',
            src: 'assets/img/DSC00293.jpg',
            thumb: 'assets/img/DSC00293.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '52',
            src: 'assets/img/DSC00326.jpg',
            thumb: 'assets/img/DSC00326.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '53',
            src: 'assets/img/DSC00370.jpg',
            thumb: 'assets/img/DSC00370.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '54',
            src: 'assets/img/DSC01496.jpg',
            thumb: 'assets/img/DSC01496.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '55',
            src: 'assets/img/DSC01539.jpg',
            thumb: 'assets/img/DSC01539.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '56',
            src: 'assets/img/DSC01543.jpg',
            thumb: 'assets/img/DSC01543.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '57',
            src: 'assets/img/DSC01579.jpg',
            thumb: 'assets/img/DSC01579.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '58',
            src: 'assets/img/DSC01755.jpg',
            thumb: 'assets/img/DSC01755.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '59',
            src: 'assets/img/DSC04130.jpg',
            thumb: 'assets/img/DSC04130.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '60',
            src: 'assets/img/DSC04301.jpg',
            thumb: 'assets/img/DSC04301.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '61',
            src: 'assets/img/DSC04512-.jpg',
            thumb: 'assets/img/DSC04512-.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '62',
            src: 'assets/img/DSC04552-.jpg',
            thumb: 'assets/img/DSC04552-.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '63',
            src: 'assets/img/DSC04572-.jpg',
            thumb: 'assets/img/DSC04572-.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '64',
            src: 'assets/img/DSC04582.jpg',
            thumb: 'assets/img/DSC04582.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '65',
            src: 'assets/img/DSC04620.jpg',
            thumb: 'assets/img/DSC04620.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '66',
            src: 'assets/img/DSC04652-.jpg',
            thumb: 'assets/img/DSC04652-.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '67',
            src: 'assets/img/DSC05021.jpg',
            thumb: 'assets/img/DSC05021.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '68',
            src: 'assets/img/DSC06760.jpg',
            thumb: 'assets/img/DSC06760.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '69',
            src: 'assets/img/DSC06880.jpg',
            thumb: 'assets/img/DSC06880.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '70',
            src: 'assets/img/DSC06896.jpg',
            thumb: 'assets/img/DSC06896.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '71',
            src: 'assets/img/DSC06905.jpg',
            thumb: 'assets/img/DSC06905.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '72',
            src: 'assets/img/DSC06947.jpg',
            thumb: 'assets/img/DSC06947.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '73',
            src: 'assets/img/DSC08046.jpg',
            thumb: 'assets/img/DSC08046.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '74',
            src: 'assets/img/DSC08670.jpg',
            thumb: 'assets/img/DSC08670.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '75',
            src: 'assets/img/DSC09289.jpg',
            thumb: 'assets/img/DSC09289.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '76',
            src: 'assets/img/DSC09389-Wiederhergestellt.jpg',
            thumb: 'assets/img/DSC09389-Wiederhergestellt.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '77',
            src: 'assets/img/DSC09442-Wiederhergestellt.jpg',
            thumb: 'assets/img/DSC09442-Wiederhergestellt.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '78',
            src: 'assets/img/DSC09539.jpg',
            thumb: 'assets/img/DSC09539.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '79',
            src: 'assets/img/DSC09592.jpg',
            thumb: 'assets/img/DSC09592.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '80',
            src: 'assets/img/DSC09602.jpg',
            thumb: 'assets/img/DSC09602.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '81',
            src: 'assets/img/DSC09839.jpg',
            thumb: 'assets/img/DSC09839.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '82',
            src: 'assets/img/DSC09862.jpg',
            thumb: 'assets/img/DSC09862.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        },
        {
            id: '83',
            src: 'assets/img/DSC09864.jpg',
            thumb: 'assets/img/DSC09864.jpg',
            format: 0,
            subHtml: 'StudioImage',
            kindOfShooting: 1,
        }
    ]
}

